# Makefile automatically generated by ghdl
# Version: GHDL 4.1.0 (Debian 4.1.0+dfsg-4) [Dunoon edition] - llvm 19.1.3 code generator
# Command used to generate this makefile:
# /usr/bin/ghdl-llvm --gen-makefile --ieee=synopsys -fexplicit --workdir=WORK matriz_celdas

GHDL=/usr/bin/ghdl-llvm
GHDLFLAGS= --ieee=synopsys -fexplicit --workdir=WORK

# Default target
all: matriz_celdas

# Elaboration target
matriz_celdas: /usr/lib/ghdl/llvm/vhdl/ieee/v93/std_logic_1164.o /usr/lib/ghdl/llvm/vhdl/ieee/v93/std_logic_1164-body.o WORK/matriz_celdas.o WORK/macro_celda.o WORK/celda_base.o
	$(GHDL) -e $(GHDLFLAGS) $@

# Run target
run: matriz_celdas
	$(GHDL) -r matriz_celdas $(GHDLRUNFLAGS)

# Targets to analyze files
/usr/lib/ghdl/llvm/vhdl/ieee/v93/std_logic_1164.o: /usr/lib/ghdl/llvm/vhdl/ieee/v93/../../src/ieee/v93/std_logic_1164.vhdl
	@echo "This file was not locally built ($<)"
	exit 1
/usr/lib/ghdl/llvm/vhdl/ieee/v93/std_logic_1164-body.o: /usr/lib/ghdl/llvm/vhdl/ieee/v93/../../src/ieee/v93/std_logic_1164-body.vhdl
	@echo "This file was not locally built ($<)"
	exit 1
WORK/matriz_celdas.o: matriz_celdas.vhd
	$(GHDL) -a $(GHDLFLAGS) $<
WORK/macro_celda.o: macro_celda.vhd
	$(GHDL) -a $(GHDLFLAGS) $<
WORK/celda_base.o: celda_base.vhd
	$(GHDL) -a $(GHDLFLAGS) $<

# Files dependences
/usr/lib/ghdl/llvm/vhdl/ieee/v93/std_logic_1164.o: 
/usr/lib/ghdl/llvm/vhdl/ieee/v93/std_logic_1164-body.o:  /usr/lib/ghdl/llvm/vhdl/ieee/v93/std_logic_1164.o
WORK/matriz_celdas.o:  /usr/lib/ghdl/llvm/vhdl/ieee/v93/std_logic_1164.o
WORK/macro_celda.o:  /usr/lib/ghdl/llvm/vhdl/ieee/v93/std_logic_1164.o
WORK/celda_base.o:  /usr/lib/ghdl/llvm/vhdl/ieee/v93/std_logic_1164.o
